/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fp_1.view.Login;

import com.fp_1.dao.UserAccount.UserAccountDao;
import com.fp_1.model.UserAccount.UserAccount;
import com.sun.mail.util.MailSSLSocketFactory;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.Message.RecipientType;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;


/**
 *
 * @author kai
 */
public class CusRegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form CusRegisterFrame
     */
    public boolean isVerified;
    public CusRegisterFrame() {
        initComponents();
        txtUserName.setEnabled(false);
        txtUserpw.setEnabled(false);
        txtUserpw2.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        regBtn = new javax.swing.JButton();
        sendBtn = new javax.swing.JButton();
        regBtn1 = new javax.swing.JButton();
        regBtn2 = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtUserpw = new javax.swing.JTextField();
        txtUserpw2 = new javax.swing.JTextField();
        verifyBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lao MN", 3, 48)); // NOI18N
        jLabel1.setText("Register");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 93, 269, 29));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Real Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 93, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 182, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 137, -1, 31));

        jLabel5.setBackground(new java.awt.Color(204, 255, 255));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 315, -1, 31));

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 364, -1, 31));

        regBtn.setBackground(new java.awt.Color(0, 153, 153));
        regBtn.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });
        getContentPane().add(regBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 518, 143, 41));

        sendBtn.setBackground(new java.awt.Color(0, 153, 153));
        sendBtn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        sendBtn.setText("Get Confirmation Code");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 41));

        regBtn1.setBackground(new java.awt.Color(0, 153, 153));
        regBtn1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        regBtn1.setText("Reset");
        regBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(regBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 518, 143, 41));

        regBtn2.setBackground(new java.awt.Color(0, 153, 153));
        regBtn2.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        regBtn2.setText("Exit");
        regBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(regBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 143, 41));

        txtEmail.setText("15359435358zck@gmail.com");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 180, 269, 30));

        jLabel7.setBackground(new java.awt.Color(204, 255, 255));
        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 413, -1, 31));

        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 250, 41));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 137, 269, 30));
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 314, 269, 30));
        getContentPane().add(txtUserpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 362, 269, 30));
        getContentPane().add(txtUserpw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 410, 269, 30));

        verifyBtn.setBackground(new java.awt.Color(0, 153, 153));
        verifyBtn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        verifyBtn.setText("Verify");
        verifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(verifyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 85, 41));

        jLabel8.setBackground(new java.awt.Color(0, 102, 102));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/kai/Downloads/255d80e4f6a6831606518e50364a3100.jpeg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtn2ActionPerformed
        JFrame thisframe =new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(thisframe,"Confirm If You Want To Exit","MySQL Connector",JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_regBtn2ActionPerformed

    private void regBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtn1ActionPerformed
        txtName.setText("");
        txtEmail.setText("");
        txtCode.setText("");
        txtPhone.setText("");
        txtUserName.setText("");
        txtUserpw.setText("");
        txtUserpw2.setText("");
    }//GEN-LAST:event_regBtn1ActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        UserAccount useraccount=new UserAccount();
        UserAccountDao useraccountDao=new UserAccountDao();
        
        
        String realname=txtName.getText();
        String phone=txtPhone.getText();
        String email=txtEmail.getText();
        // say hi!
       
        
        
        String username=txtUserName.getText();//verify username
        if (useraccountDao.isUsernameExist(username))
        {
            JOptionPane.showMessageDialog(this, "Unique UserName Required");
            //txtName.setText("");
            txtUserName.setText("");
            txtUserpw.setText("");
            txtUserpw2.setText("");
            return;
        }


        String userpw=txtUserpw.getText();//verify pw
        String userpw2=txtUserpw2.getText();
        boolean isSame=false;
        if(!userpw.equals(userpw2))
        {
            JOptionPane.showMessageDialog(this, "Identical Password Required");
            txtUserpw.setText("");
            txtUserpw2.setText("");
        }
        else
        {
            isSame=true;
        }
        
        if(isSame)//update the info to the table 
        {
            useraccount.setUserIdentity("Customer");
            useraccount.setUserName(username);
            useraccount.setUserPassword(userpw2);
            useraccount.setEmail(email);
            useraccount.setPhone(phone);
            useraccount.setRealName(realname);
            
            useraccountDao.add(useraccount);
            
            JOptionPane.showMessageDialog(this, "Register Successful!");
            txtName.setText("");
            txtEmail.setText("");
            txtCode.setText("");
            txtPhone.setText("");
            txtUserName.setText("");
            txtUserpw.setText("");
            txtUserpw2.setText("");
            
        }
    }//GEN-LAST:event_regBtnActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        try
        {
            MailSSLSocketFactory sf = new MailSSLSocketFactory();
            sf.setTrustAllHosts(true);
            String toEmail=txtEmail.getText();
            
            Properties properties=new Properties();
            properties.put("mail.transport.protocol","smtp");
            properties.put("mail.smtp.auth","true");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.host","smtp.qq.com");
            properties.setProperty("mail.debug", "true");
            
            //properties.put("mail.smtp.port", "587");
            
            properties.put("mail.user", "770823669@qq.com");
            properties.put("mail.password", "ygyihhfwzvfybcfa");
            properties.put("mail.smtp.ssl.enable", "true");
            properties.put("mail.smtp.ssl.socketFactory", sf);
            
            
            Session session=Session.getDefaultInstance(properties,new Authenticator()
                {
                    @Override 
                    protected PasswordAuthentication getPasswordAuthentication(){
                        // TODO 
                        return new PasswordAuthentication("770823669@qq.com","ygyihhfwzvfybcfa");
                    }
                });
            
            Message message=new MimeMessage(session);
            message.setSubject("Verification Email");
            message.setContent("Hi! This is the verification email of the project! The verification code is 12345!","text/plain");
            message.setFrom(new InternetAddress("770823669@qq.com"));
            message.setRecipient(RecipientType.TO, new InternetAddress(toEmail));
            message.setSentDate(new Date());

            Transport.send(message);
            JOptionPane.showMessageDialog(null, "Sent");
        
        
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void verifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyBtnActionPerformed
        if (txtCode.getText().equals("12345"))
        {
            JOptionPane.showMessageDialog(this, "Email Verified!");
            isVerified=true;
            txtUserName.setEnabled(true);
            txtUserpw.setEnabled(true);
            txtUserpw2.setEnabled(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Verification Failed");
            isVerified=false;
        }

    }//GEN-LAST:event_verifyBtnActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CusRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CusRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CusRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CusRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CusRegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton regBtn;
    private javax.swing.JButton regBtn1;
    private javax.swing.JButton regBtn2;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserpw;
    private javax.swing.JTextField txtUserpw2;
    private javax.swing.JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
}
