/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fp_1.view.Login;

import com.fp_1.view.Dealership.WholeCarPurchase;
import com.fp_1.view.Dealership.WholeCarPurchaseManage;
import com.fp_1.view.ManufactureMain;
import com.fp_1.view.Supplier.SupplierMainFrame;
import com.fp_1.view.SysAdmin.SysAdminFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kai
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public String sysadUser="1";
    public String sysadPw="1";
    
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBtn = new javax.swing.JButton();
        clrBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idBox = new javax.swing.JComboBox<>();
        txtUser = new javax.swing.JTextField();
        pwPassword = new javax.swing.JPasswordField();
        clrBtn = new javax.swing.JButton();
        regBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn.setBackground(new java.awt.Color(0, 153, 153));
        loginBtn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 292, 107, 50));

        clrBtn1.setBackground(new java.awt.Color(0, 153, 153));
        clrBtn1.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        clrBtn1.setText("Exit");
        clrBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(clrBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 107, 45));

        jLabel1.setFont(new java.awt.Font("Lao MN", 3, 48)); // NOI18N
        jLabel1.setText("Login ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UserName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 185, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 232, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select Identity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 138, -1, -1));

        idBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier-MP", "Supplier-PP", "Supplier-PS", "Supplier-Admin", "Dealer-Admin", "Customer", "Manufacture-PP", "Manufacture-AS", "Manufacture-Admin", "System Admin", " " }));
        idBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBoxActionPerformed(evt);
            }
        });
        getContentPane().add(idBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 138, 213, 29));
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 185, 269, 29));
        getContentPane().add(pwPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 232, 269, 29));

        clrBtn.setBackground(new java.awt.Color(0, 153, 153));
        clrBtn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        clrBtn.setText("Clear");
        clrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 292, 107, 45));

        regBtn.setBackground(new java.awt.Color(0, 153, 153));
        regBtn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });
        getContentPane().add(regBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 292, 107, 45));

        jLabel8.setBackground(new java.awt.Color(0, 102, 102));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/kai/Downloads/255d80e4f6a6831606518e50364a3100.jpeg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        String loginNa=txtUser.getText();
        String loginPw=pwPassword.getText();

        Object idslct;
        idslct=idBox.getSelectedItem();



        //JOptionPane.showMessageDialog(this, idslct.toString());
        if (idslct.toString()=="System Admin"){
            //sysAdminFrame.setUserIdentity("Sys");
            if (loginNa.equals(sysadUser) & loginPw.equals(sysadPw))
            {
               
                txtUser.setText("");
                pwPassword.setText("");

                SysAdminFrame sysadminFrame=new SysAdminFrame("SysAdmin");
                sysadminFrame.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "No Such SysAdmin In System");
                txtUser.setText("");
                pwPassword.setText("");
                return;
            }
            //this.setVisible(false);
        }

        if (idslct.toString()=="Supplier-MP"){
            boolean isin=false;
            if (loginPw.equals("aaaa"))
            {
                JOptionPane.showMessageDialog(this, "Wrong Password!");
                txtUser.setText("");
                pwPassword.setText("");
                return;
            }
            SupplierMainFrame supplierFrame=new SupplierMainFrame("MaterialPurchase");
            supplierFrame.setVisible(true);

            //this.setVisible(false);
        }

        if (idslct.toString()=="Supplier-PP"){
            boolean isin=false;
            if (loginPw.equals("aaaa"))
            {
                JOptionPane.showMessageDialog(this, "Wrong Password!");
                txtUser.setText("");
                pwPassword.setText("");
                return;
            }
            //sysAdminFrame.setUserIdentity("Hos");
            //JOptionPane.showMessageDialog(this, idslct.toString());
            SupplierMainFrame supplierFrame=new SupplierMainFrame("PartProducing");
            supplierFrame.setVisible(true);
            /*if (!isin){
                JOptionPane.showMessageDialog(this, "No Such HosAdmin In System");
                txtUser.setText("");
                pwPassword.setText("");
            }*/
            //this.setVisible(false);
        }

        if (idslct.toString()=="Supplier-PS"){
            boolean isin=false;
            if (loginPw.equals("aaaa"))
            {
                JOptionPane.showMessageDialog(this, "Wrong Password!");
                txtUser.setText("");
                pwPassword.setText("");
                return;
            }
            SupplierMainFrame supplierFrame=new SupplierMainFrame("PartSelling");
            supplierFrame.setVisible(true);
            //this.setVisible(false);
        }
        
        if (idslct.toString()=="Supplier-Admin"){
            boolean isin=false;
            if (loginPw.equals("aaaa"))
            {
                JOptionPane.showMessageDialog(this, "Wrong Password!");
                txtUser.setText("");
                pwPassword.setText("");
                return;
            }
            SupplierMainFrame supplierFrame=new SupplierMainFrame("Admin");
            supplierFrame.setVisible(true);
            //this.setVisible(false);
        }
        
        if (idslct.toString()=="Dealer-Admin"){
            boolean isin=false;
            if (loginPw.equals("aaaa"))
            {
                JOptionPane.showMessageDialog(this, "Wrong Password!");
                txtUser.setText("");
                pwPassword.setText("");
                return;
            }
            WholeCarPurchaseManage wp=new WholeCarPurchaseManage();
            wp.setVisible(true);
            //this.setVisible(false);
        }
        
        if (idslct.toString()=="Customer"){
            boolean isin=false;
            if (loginPw.equals("aaaa"))
            {
                JOptionPane.showMessageDialog(this, "Wrong Password!");
                txtUser.setText("");
                pwPassword.setText("");
                return;
            }
            WholeCarPurchase wp=new WholeCarPurchase(loginNa);
            wp.setVisible(true);
            //this.setVisible(false);
        }
        
        if (idslct.toString()=="Manufacture-Admin"){
            boolean isin=false;
            if (loginPw.equals("aaaa"))
            {
                JOptionPane.showMessageDialog(this, "Wrong Password!");
                txtUser.setText("");
                pwPassword.setText("");
                return;
            }
            ManufactureMain mm=new ManufactureMain("Admin");
            mm.setVisible(true);
            //this.setVisible(false);
        }
        
        if (idslct.toString()=="Manufacture-PP"){
            boolean isin=false;

            ManufactureMain mm=new ManufactureMain("PP");
            mm.setVisible(true);
            //this.setVisible(false);
        }
        
        if (idslct.toString()=="Manufacture-AS"){
            boolean isin=false;

            ManufactureMain mm=new ManufactureMain("AS");
            mm.setVisible(true);
            //this.setVisible(false);
        }
        
        
        
        if (idslct.toString()=="Manufacture-Admin"){
            boolean isin=false;

            ManufactureMain mm=new ManufactureMain("AS");
            mm.setVisible(true);
            //this.setVisible(false);
        }

        /*if (idslct.toString()=="Doctor"){
            boolean isin=false;
            for (Doctor dp:dDirectory.getHistory())
            {
                if(loginNa.equals(dp.getMeUser().getUserName()) & loginPw.equals(dp.getMeUser().getUserPassword()) )
                {
                    txtUser.setText("");
                    pwPassword.setText("");
                    String pid=dp.getDoctorID();
                    doctorFrame doctorFrame = new doctorFrame(pDirectory,dDirectory,eHistory,hDirectory,pid);
                    doctorFrame.setVisible(true);
                    isin=true;
                }

            }
            if (!isin){
                JOptionPane.showMessageDialog(this, "No Such Doctor In System");
                txtUser.setText("");
                pwPassword.setText("");
            }

            //this.setVisible(false);
        }*/

    }//GEN-LAST:event_loginBtnActionPerformed

    private void clrBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtn1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_clrBtn1ActionPerformed

    private void idBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idBoxActionPerformed

    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        txtUser.setText("");
        pwPassword.setText("");
    }//GEN-LAST:event_clrBtnActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed

        CusRegisterFrame cusreg=new CusRegisterFrame();
        cusreg.setVisible(true);
    }//GEN-LAST:event_regBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clrBtn;
    private javax.swing.JButton clrBtn1;
    private javax.swing.JComboBox<String> idBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField pwPassword;
    private javax.swing.JButton regBtn;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
