/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fp_1.view.Dealership;

import com.fp_1.dao.Dealership.DealershipDao;
import com.fp_1.dao.WholeCarPurchase.CarPurchaseDao;
import com.fp_1.model.WholeCarPurchase.CarPurchase;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author yiyangzhou
 */
public class ConfirmBuying extends javax.swing.JFrame {
    String username;
    int VIN;
    CarPurchase carpurchase;
    
    /**
     * Creates new form ConfirmBuying
     */
    public ConfirmBuying(String username, int VIN) {
        this.username = username;
        this.VIN = VIN;
        initComponents();
    }
    
    public ConfirmBuying(CarPurchase carpurchase) {
        this.carpurchase = carpurchase;
        initComponents();
        populate();
    }
    
    private void populate(){
        addrLine1.setText(carpurchase.getAddress1());
        addrLine2.setText(carpurchase.getAddress2());
        shipCombo.setSelectedItem(carpurchase.getShipment());

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyInfoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addrLine1 = new javax.swing.JTextField();
        addrLine2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        shipCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cashRadio = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        visaRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buyInfoBtn.setText("Confirm");
        buyInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyInfoBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Address line 1");

        jLabel2.setText("Address line 2");

        addrLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrLine2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Shipment");

        shipCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Buy Online", "Ship", "Reserve", " " }));

        jLabel5.setText("Payment");

        cashRadio.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cashRadio.setForeground(new java.awt.Color(204, 51, 0));
        cashRadio.setText("Cash");
        cashRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRadioActionPerformed(evt);
            }
        });

        ImageIcon imagevisa = new ImageIcon("/Users/kai/Desktop/develop/aes_final/src/main/java/images/VISA.png");
        imagevisa.setImage(imagevisa.getImage().getScaledInstance(200, 70, Image.SCALE_DEFAULT ));
        jLabel6.setIcon(imagevisa);

        visaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(81, 81, 81)
                        .addComponent(addrLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashRadio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(visaRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addrLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shipCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(buyInfoBtn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addrLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addrLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shipCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(cashRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visaRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buyInfoBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void buyInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyInfoBtnActionPerformed
        WholeCarPurchase wholeCarPurchase = new WholeCarPurchase();

        if(this.carpurchase!=null){
            CarPurchaseDao carpurchasedao = new CarPurchaseDao();
            String addrline1 = addrLine1.getText();
            if(addrline1.equals(null)){
                JOptionPane.showMessageDialog(this, "Address Line 1 empty");
                return;
        }
            String addrline2 = addrLine2.getText();
            String shipment = (String) shipCombo.getSelectedItem();
            if(shipment.equals(" ")){
                JOptionPane.showMessageDialog(this, "Choose one shipment method");
                
             return;
        }
            
            this.carpurchase.setAddress1(addrline1);
            this.carpurchase.setAddress2(addrline2);
            this.carpurchase.setShipment(shipment);
            
            carpurchasedao.updateEdit(this.carpurchase);
            
            JOptionPane.showMessageDialog(this, "Edit successfully");
            this.dispose();
            wholeCarPurchase.populateResultTable2();

            return;
        }
        
        String orderStatus = "Orderd";
        String addr1 = addrLine1.getText(); 
        Date now = new Date();
        if(addr1.equals(null)){
            JOptionPane.showMessageDialog(this, "Address Line 1 empty");
            return;
        }
        
        String addr2 = addrLine2.getText();
        String shipment = (String) shipCombo.getSelectedItem();
        if(shipment.equals(" ")){
            JOptionPane.showMessageDialog(this, "Choose one shipment method");
            return;
        }
        String username2 = this.username;
        int VIN = this.VIN;
        
        CarPurchase carPurchase = new CarPurchase();
        carPurchase.setAddress1(addr1);
        carPurchase.setAddress2(addr2);
        carPurchase.setCreateTime(now);
        carPurchase.setOrderStatus("Ordered");
        carPurchase.setShipment(shipment);
        carPurchase.setUserName(username);
        carPurchase.setVIN(this.VIN);
        
        CarPurchaseDao carpurchasedao = new CarPurchaseDao();
        carpurchasedao.add(carPurchase);
        JOptionPane.showMessageDialog(null, "Add successfully");
        
        this.dispose();
        this.carpurchase = null;
        DealershipDao dealershipDao = new DealershipDao();
        dealershipDao.delete(VIN);
        
        wholeCarPurchase.populateResultTable2();
        
    }//GEN-LAST:event_buyInfoBtnActionPerformed

    private void addrLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrLine2ActionPerformed

    private void visaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaRadioActionPerformed

        if(visaRadio.isSelected()){
            cashRadio.setSelected(false);
            
        }    }//GEN-LAST:event_visaRadioActionPerformed

    private void cashRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRadioActionPerformed
        if(cashRadio.isSelected()){
            visaRadio.setSelected(false);
            }       
    }//GEN-LAST:event_cashRadioActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConfirmBuying.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConfirmBuying.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConfirmBuying.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConfirmBuying.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConfirmBuying().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField addrLine1;
    public javax.swing.JTextField addrLine2;
    private javax.swing.JButton buyInfoBtn;
    public javax.swing.JRadioButton cashRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JComboBox<String> shipCombo;
    public javax.swing.JRadioButton visaRadio;
    // End of variables declaration//GEN-END:variables
}
