/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fp_1.view.ChartPainting;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author kai
 */
public class ChartPaintPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChartPaintPanel
     */
    public ChartPaintPanel() {
        initComponents();

    }

    int HEIGHT = 250;
    int offsetY = 14;// y axis offset for text to be above the chart
    Font font = new Font("Times", Font.BOLD, 18);

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        HEIGHT = (int) (getHeight());
        int width = getWidth();

        int w80 = (int) (width * 0.8);// the 80% of the width of the page
        int w20 = (int) (width * 0.2);
        int bottom = getHeight() - 20; // actually the top instead
        
        //JOptionPane.showMessageDialog(this, bottom);

        int uw = w80 / 4; // the column width
        int gap = w20 / 5; // the gap width

        int rectH = (int) (HEIGHT * 0.2);// each percent present as the percent of the Height
        String str;
        g.setFont(font);

        Color charc = new Color(44, 62, 80);
        g.setColor(charc);

        g.fillRect(gap, bottom - rectH, uw, rectH);
        g.setColor(Color.BLACK);
        str = "Project -- 20%";
        g.drawString(str, gap, bottom - rectH - offsetY);

        rectH = (int) (HEIGHT * 0.1);
        g.setColor(Color.BLUE);
        g.fillRect(gap * 2 + uw, bottom - rectH, uw, rectH);
        g.setColor(Color.BLACK);
        str = "Quizzes -- 10%";
        g.drawString(str, gap * 2 + uw, bottom - rectH - offsetY);

        rectH = (int) (HEIGHT * 0.3);
        g.setColor(Color.GREEN);
        g.fillRect(gap * 3 + uw * 2, bottom - rectH, uw, rectH);
        g.setColor(Color.BLACK);
        str = "Midtems -- 30%";
        g.drawString(str, gap * 3 + uw * 2, bottom - rectH - offsetY);

        rectH = (int) (HEIGHT * 0.4);
        g.setColor(Color.ORANGE);
        g.fillRect(gap * 4 + uw * 3, bottom - rectH, uw, rectH);
        g.setColor(Color.BLACK);
        str = "Final -- 40%";
        g.drawString(str, gap * 4 + uw * 3, bottom - rectH - offsetY);

        int x1, x2, y1, y2;
        x1 = gap / 2;
        y1 = bottom;
        x2 = width - gap / 2;
        y2 = y1;
        g.setColor(Color.BLACK);
        g.drawLine(x1, y1, x2, y2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
